ERROR 2023-09-12 20:22:46,028  Internal Server Error: /news/ C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\utils\log.py, (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('news/post_list.html'), <traceback object at 0x000002EFBFD2DC80>)
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
ERROR 2023-09-12 20:22:46,030  "GET /news/ HTTP/1.1" 500 87936 C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\servers\basehttp.py, None
