ERROR 2023-09-12 20:22:46,028  Internal Server Error: /news/ C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\utils\log.py, (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('news/post_list.html'), <traceback object at 0x000002EFBFD2DC80>)
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
ERROR 2023-09-12 20:22:46,030  "GET /news/ HTTP/1.1" 500 87936 C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\servers\basehttp.py, None
ERROR 2023-09-15 17:14:53,999  Internal Server Error: /news/ C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\utils\log.py, (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError('Unknown argument for \'trans\' tag: \'нет\'. The only options available are \'noop\', \'context\' "xxx", and \'as VAR\'.'), <traceback object at 0x0000028E7008E640>)
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\templatetags\i18n.py", line 443, in do_translate
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Unknown argument for 'trans' tag: 'нет'. The only options available are 'noop', 'context' "xxx", and 'as VAR'.
ERROR 2023-09-15 17:14:54,003  "GET /news/ HTTP/1.1" 500 231666 C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\servers\basehttp.py, None
ERROR 2023-09-16 14:19:04,546  Internal Server Error: /news/ C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\utils\log.py, (<class 'AttributeError'>, AttributeError("'PostList' object has no attribute 'form_class'"), <traceback object at 0x0000020BA6307C00>)
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
  File "C:\Users\1\PycharmProjects\Project_dir\project\news\views.py", line 45, in get_context_data
    context['form'] = self.form_class()  # создаем экземпл€р формы, чтобы передать в контекст
AttributeError: 'PostList' object has no attribute 'form_class'
ERROR 2023-09-16 14:19:04,548  "GET /news/ HTTP/1.1" 500 90297 C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\servers\basehttp.py, None
ERROR 2023-09-16 14:19:50,491  Internal Server Error: /news/ C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\utils\log.py, (<class 'AttributeError'>, AttributeError("'PostList' object has no attribute 'form_class'"), <traceback object at 0x000002909F4D9300>)
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\project\news\views.py", line 51, in post
    form = self.form_class(request.POST)
AttributeError: 'PostList' object has no attribute 'form_class'
ERROR 2023-09-16 14:19:50,493  "POST /news/ HTTP/1.1" 500 84998 C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\servers\basehttp.py, None
ERROR 2023-09-16 14:21:17,478  Internal Server Error: /news/ C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\utils\log.py, (<class 'AttributeError'>, AttributeError("'PostList' object has no attribute 'form_class'"), <traceback object at 0x000001B9E709CC80>)
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\project\news\views.py", line 52, in post
    form = self.form_class(request.POST)
AttributeError: 'PostList' object has no attribute 'form_class'
ERROR 2023-09-16 14:21:17,481  "POST /news/ HTTP/1.1" 500 85084 C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\servers\basehttp.py, None
ERROR 2023-09-16 14:21:23,471  Internal Server Error: /news/ C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\utils\log.py, (<class 'AttributeError'>, AttributeError("'PostList' object has no attribute 'form_class'"), <traceback object at 0x000001B9E6ED7BC0>)
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
  File "C:\Users\1\PycharmProjects\Project_dir\project\news\views.py", line 45, in get_context_data
    context['form'] = self.form_class()  # создаем экземпл€р формы, чтобы передать в контекст
AttributeError: 'PostList' object has no attribute 'form_class'
ERROR 2023-09-16 14:21:23,474  "GET /news/ HTTP/1.1" 500 90004 C:\Users\1\PycharmProjects\Project_dir\venv\lib\site-packages\django\core\servers\basehttp.py, None
